import {Genders} from '../../../constants';

export enum Age {
	Around30s = 'Around 30s',
	Around60s = 'Around 60s',
	Child = 'Child',
	MiddleAged = 'Middle-aged',
	Old = 'Elderly',
	Teenager = 'Teenager',
	VeryOld = 'Very old',
	YoungAdult = 'Young Adult',
}

export enum CharColor {
	Amber = 'amber',
	Auburn = 'auburn',
	Black = 'black',
	BlackNoPupils = 'black [STARE] eyes with no pupils',
	Blond = 'blond',
	Blue = 'blue',
	Brown = 'brown',
	Chestnut = 'chestnut brown',
	Copper = 'copper',
	DarkBlond = 'dark blond',
	DarkBrown = 'dark brown',
	Ginger = 'ginger red',
	Golden = 'golden blond',
	Gray = 'gray',
	Green = 'green',
	Greenish = 'greenish',
	Hazel = 'hazel',
	LightBlond = 'light blond',
	LightBlue = 'light blue',
	LightBrown = 'light brown',
	LightGray = 'light gray',
	LightGreen = 'light green',
	PaleBlue = 'pale blue',
	PaleBlueYellowSpots = 'pale blue [STARE] eyes with yellow spots',
	Purple = 'purple',
	Red = 'red',
	Reddish = 'reddish',
	SilverBlond = 'silver blond',
	Unnatural = 'unnatural colored',
	VibrantRed = 'vibrant red',
	White = 'white',
	WhiteNoPupils = 'white [STARE] eyes with no pupils',
	Yellow = 'yellow',
	YellowCat = 'yellow cat-like',
}

export enum Height {
	Average = 'Average height',
	Short = 'Short',
	Tall = 'Tall',
	VeryShort = 'Very short',
	VeryTall = 'Very tall',
}

export enum Weight {
	Athletic = 'athletic',
	Atrophied = 'atrophied',
	Average = 'average',
	BarrelChested = 'barrel-chested',
	BeerBellied = 'beer-bellied',
	BroadShouldered = 'broad-shouldered',
	Bulky = 'bulky',
	Chubby = 'chubby',
	Curvaceous = 'curvaceous',
	Decrepit = 'decrepit',
	Defined = 'defined',
	Doughy = 'doughy',
	ExtremelyOverweight = 'extremely overweight',
	Fit = 'fit',
	Frail = 'frail',
	Healthy = 'healthy',
	Herculean = 'herculean',
	HourglassShaped = 'hourglass-shaped',
	Hulking = 'hulking',
	MildlyOverweight = 'mildly overweight',
	Muscular = 'muscular',
	Narrow = 'narrow',
	PearShaped = 'pear-shaped',
	Petite = 'petite',
	Round = 'round',
	Scrawny = 'scrawny',
	Skinny = 'skinny',
	Starved = 'starved',
	Stout = 'stout',
	ThickWaisted = 'thick-waisted',
	Thin = 'thin',
	Underweight = 'underweight',
}

export const DESCENDENCE_TEXT = {
	[Genders.Woman]: 'Daughter of a/an',
	[Genders.Man]: 'Son of a/an',
	[Genders.GNC]: 'Child of a/an',
};

export const YOUNG_GENDER = {
	[Genders.Woman]: 'girl',
	[Genders.Man]: 'boy',
	[Genders.GNC]: 'child',
};
