import {CharColor} from './constants';
import {Ancestries} from '../../../constants';

export const HAIR_COLORS = [
	CharColor.Auburn,
	CharColor.Black,
	CharColor.Blond,
	CharColor.Blue,
	CharColor.Chestnut,
	CharColor.Copper,
	CharColor.DarkBrown,
	CharColor.Ginger,
	CharColor.Golden,
	CharColor.Greenish,
	CharColor.Green,
	CharColor.Gray,
	CharColor.LightBlond,
	CharColor.Brown,
	CharColor.DarkBlond,
	CharColor.Purple,
	CharColor.SilverBlond,
	CharColor.VibrantRed,
	CharColor.White,
	CharColor.Unnatural,
];

export const PREDOMINANT_HAIR_COLOR_BY_ANCESTRY = {
	[Ancestries.Anglosaxon]: [
		CharColor.Black,
		CharColor.Blond,
		CharColor.Auburn,
		CharColor.Chestnut,
		CharColor.DarkBrown,
		CharColor.Copper,
		CharColor.Golden,
		CharColor.Brown,
		CharColor.LightBlond,
		CharColor.Ginger,
		CharColor.DarkBlond,
	],
	[Ancestries.African]: [CharColor.Black],
	[Ancestries.Arabic]: [CharColor.Black, CharColor.DarkBrown],
	[Ancestries.Chinese]: [CharColor.Black],
	[Ancestries.Dutch]: [
		CharColor.Auburn,
		CharColor.DarkBrown,
		CharColor.LightBlond,
		CharColor.Ginger,
		CharColor.DarkBlond,
		CharColor.Chestnut,
		CharColor.Copper,
	],
	[Ancestries.Eastern]: [
		CharColor.Blond,
		CharColor.Auburn,
		CharColor.Chestnut,
		CharColor.DarkBrown,
		CharColor.Golden,
		CharColor.Brown,
		CharColor.LightBlond,
		CharColor.DarkBlond,
	],
	[Ancestries.French]: [
		CharColor.Black,
		CharColor.Blond,
		CharColor.Chestnut,
		CharColor.DarkBrown,
		CharColor.Copper,
		CharColor.Brown,
		CharColor.LightBlond,
		CharColor.Ginger,
		CharColor.DarkBlond,
	],
	[Ancestries.Germanic]: [
		CharColor.Black,
		CharColor.Blond,
		CharColor.DarkBrown,
		CharColor.Golden,
		CharColor.Brown,
		CharColor.LightBlond,
		CharColor.DarkBlond,
	],
	[Ancestries.Indian]: [CharColor.Black, CharColor.DarkBrown],
	[Ancestries.Irish]: [
		CharColor.Black,
		CharColor.Blond,
		CharColor.Auburn,
		CharColor.Chestnut,
		CharColor.DarkBrown,
		CharColor.Copper,
		CharColor.Brown,
		CharColor.LightBlond,
		CharColor.Ginger,
		CharColor.DarkBlond,
		CharColor.VibrantRed,
	],
	[Ancestries.Ironlander]: [
		CharColor.Auburn,
		CharColor.Black,
		CharColor.Blond,
		CharColor.Chestnut,
		CharColor.Copper,
		CharColor.DarkBrown,
		CharColor.Ginger,
		CharColor.Golden,
		CharColor.LightBlond,
		CharColor.Brown,
		CharColor.DarkBlond,
		CharColor.SilverBlond,
		CharColor.VibrantRed,
	],
	[Ancestries.Italian]: [
		CharColor.Black,
		CharColor.Blond,
		CharColor.Chestnut,
		CharColor.DarkBrown,
		CharColor.Copper,
		CharColor.Brown,
		CharColor.DarkBlond,
	],
	[Ancestries.Japanese]: [CharColor.Black],
	[Ancestries.Korean]: [CharColor.Black],
	[Ancestries.Norse]: [
		CharColor.Blond,
		CharColor.Chestnut,
		CharColor.Golden,
		CharColor.LightBlond,
		CharColor.DarkBlond,
		CharColor.SilverBlond,
	],
	[Ancestries.Portuguese]: [
		CharColor.Black,
		CharColor.Blond,
		CharColor.Chestnut,
		CharColor.DarkBrown,
		CharColor.Copper,
		CharColor.Brown,
		CharColor.DarkBlond,
	],
	[Ancestries.Russian]: [
		CharColor.Blond,
		CharColor.Auburn,
		CharColor.Chestnut,
		CharColor.Copper,
		CharColor.DarkBrown,
		CharColor.Golden,
		CharColor.Brown,
		CharColor.LightBlond,
		CharColor.DarkBlond,
	],
	[Ancestries.Spanish]: [
		CharColor.Black,
		CharColor.Blond,
		CharColor.Chestnut,
		CharColor.DarkBrown,
		CharColor.Copper,
		CharColor.Brown,
		CharColor.DarkBlond,
	],
	[Ancestries.Fantastic]: [
		CharColor.Auburn,
		CharColor.Black,
		CharColor.Blond,
		CharColor.Blue,
		CharColor.Chestnut,
		CharColor.Copper,
		CharColor.DarkBrown,
		CharColor.Ginger,
		CharColor.Golden,
		CharColor.Greenish,
		CharColor.Gray,
		CharColor.LightBlond,
		CharColor.Brown,
		CharColor.DarkBlond,
		CharColor.Purple,
		CharColor.SilverBlond,
		CharColor.VibrantRed,
		CharColor.White,
		CharColor.Unnatural,
	],
};

export const FACIAL_HAIR = [
	'Clean-shaven face',
	'Stubbled face',
	'Scruffy facial hair',
	'Goatee beard',
	'Bushy mustache',
	'Clean-shaven face',
	'Thin mustache',
	'Wide mustache',
	'Mutton chops',
	'Full beard',
	'Clean-shaven face',
	'Full beard',
	'Ducktail beard',
	'French fork bearded',
	'Long braided beard hair',
	'Chin curtain',
	'Verdi beard',
	'Garibaldi beard',
	'Garibaldi beard',
	'Clean-shaven face',
	'Long straight beard hair',
	'Circle beard',
	'Full beard',
	'Goatee beard',
	'Extended goatee beard',
	'Horseshoe mustache',
	'Clean-shaven face',
	'Side whiskers',
	'Zappa mustache',
	'Hulheee beard',
	'Anchor beard',
	'Clean-shaven face',
	'Stubbed face',
	'Soul patch beard',
	'Bandholz beard',
	'Long frizzy and dirty beard',
	'Bandholz beard',
	'Long frizzy and dirty beard',
	'Van dyke beard',
	'Clean-shaven face',
];

export const HAIR_STYLE_FEMALE = [
	'Long wavy [COLOR] hair',
	'Long straight [COLOR] hair',
	'Long curly [COLOR] hair',
	'Long frizzy [COLOR] hair',
	'Long wavy [COLOR] hair',
	'Long straight [COLOR] hair',
	'Long curly [COLOR] hair',
	'Long frizzy [COLOR] hair',
	'Long wavy [COLOR] hair',
	'Long straight [COLOR] hair',
	'Long curly [COLOR] hair',
	'Long frizzy [COLOR] hair',
	'Long wavy [COLOR] hair',
	'Long straight [COLOR] hair',
	'Long curly [COLOR] hair',
	'Long frizzy [COLOR] hair',
	'Long [COLOR] hair with dreadlocks',
	'Long [COLOR] hair with waterfall braids',
	'Long fish braided [COLOR] hair',
	'Long loose braided [COLOR] hair',
	'Long french braided [COLOR] hair',
	'Long french braided [COLOR] hair',
	'Long dutch braided [COLOR] hair',
	'Long dutch braided [COLOR] hair',
	'Long [COLOR] hair with a ponytail',
	'Long [COLOR] hair with a side ponytail',
	'Long [COLOR] hair with two childish ponytails',
	'Long [COLOR] hair with two dutch braids',
	'Long [COLOR] hair with two dutch braids',
	'Long [COLOR] hair with cornrows',
	'Long maid braided [COLOR] hair',
	'Long maid braided [COLOR] hair',
	'Long plait braided [COLOR] hair',
	'Shoulder length wavy [COLOR] hair',
	'Shoulder length straight [COLOR] hair',
	'Shoulder length curly [COLOR] hair',
	'Shoulder length frizzy [COLOR] hair',
	'Shoulder length wavy [COLOR] hair',
	'Shoulder length straight [COLOR] hair',
	'Shoulder length curly [COLOR] hair',
	'Shoulder length frizzy [COLOR] hair',
	'Shoulder length wavy [COLOR] hair',
	'Shoulder length straight [COLOR] hair',
	'Shoulder length curly [COLOR] hair',
	'Shoulder length frizzy [COLOR] hair',
	'Shoulder length wavy [COLOR] hair',
	'Shoulder length straight [COLOR] hair',
	'Shoulder length curly [COLOR] hair',
	'Shoulder length frizzy [COLOR] hair',
	'Shoulder length [COLOR] hair with dreadlocks',
	'Shoulder length [COLOR] hair with waterfall braids',
	'Shoulder length fish braided [COLOR] hair',
	'Shoulder length fish braided [COLOR] hair',
	'Shoulder length loose braided [COLOR] hair',
	'Shoulder length loose braided [COLOR] hair',
	'Shoulder length french braided [COLOR] hair',
	'Shoulder length dutch braided [COLOR] hair',
	'Shoulder length french braided [COLOR] hair',
	'Shoulder length dutch braided [COLOR] hair',
	'Shoulder length dutch braided [COLOR] hair',
	'Shoulder length [COLOR] hair with a ponytail',
	'Shoulder length [COLOR] hair with a side ponytail',
	'Shoulder length [COLOR] hair with two childish ponytails',
	'Shoulder length [COLOR] hair with two dutch braids',
	'Shoulder length [COLOR] hair with two dutch braids',
	'Shoulder length [COLOR] hair with two dutch braids',
	'Shoulder length [COLOR] hair with cornrows',
	'Shoulder length maid braided [COLOR] hair',
	'Shoulder length maid braided [COLOR] hair',
	'Shoulder length plait braided [COLOR] hair',
	'Short wavy [COLOR] hair',
	'Short straight [COLOR] hair',
	'Short curly [COLOR] hair',
	'Short frizzy [COLOR] hair',
	'Short wavy [COLOR] hair',
	'Short straight [COLOR] hair',
	'Short curly [COLOR] hair',
	'Short frizzy [COLOR] hair',
	'Short wavy [COLOR] hair',
	'Short straight [COLOR] hair',
	'Short curly [COLOR] hair',
	'Short frizzy [COLOR] hair',
	'Short [COLOR] hair with dreadlocks',
	'Short [COLOR] hair with cornrows',
	'Short bob [COLOR] hair',
	'Short messy [COLOR] hair',
	'Short cropped [COLOR] hair',
	'Short messy [COLOR] hair',
	'Short cropped [COLOR] hair',
	'Short spiked [COLOR] hair',
	'Short flat top [COLOR] hair',
	'Short crew cut [COLOR] hair',
	'Short shaved [COLOR] hair',
	'Shaved head',
];

export const HAIR_STYLE_MALE = [
	'Long wavy [COLOR] hair',
	'Long straight [COLOR] hair',
	'Long curly [COLOR] hair',
	'Long frizzy [COLOR] hair',
	'Long wavy [COLOR] hair',
	'Long straight [COLOR] hair',
	'Long curly [COLOR] hair',
	'Long frizzy [COLOR] hair',
	'Long wavy [COLOR] hair',
	'Long straight [COLOR] hair',
	'Long curly [COLOR] hair',
	'Long frizzy [COLOR] hair',
	'Long [COLOR] hair with dreadlocks',
	'Long [COLOR] hair with waterfall braids',
	'Long fish braided [COLOR] hair',
	'Long dutch braided [COLOR] hair',
	'Long [COLOR] hair with a ponytail',
	'Long cornrows [COLOR] hair',
	'Shoulder length wavy [COLOR] hair',
	'Shoulder length straight [COLOR] hair',
	'Shoulder length curly [COLOR] hair',
	'Shoulder length frizzy [COLOR] hair',
	'Shoulder length wavy [COLOR] hair',
	'Shoulder length straight [COLOR] hair',
	'Shoulder length curly [COLOR] hair',
	'Shoulder length frizzy [COLOR] hair',
	'Shoulder length wavy [COLOR] hair',
	'Shoulder length straight [COLOR] hair',
	'Shoulder length curly [COLOR] hair',
	'Shoulder length frizzy [COLOR] hair',
	'Shoulder length [COLOR] hair with dreadlocks',
	'Shoulder length [COLOR] hair with waterfall braids',
	'Shoulder length fish braided [COLOR] hair',
	'Shoulder length dutch braided [COLOR] hair',
	'Shoulder length [COLOR] hair with a ponytail',
	'Shoulder length cornrows [COLOR] hair',
	'Short wavy [COLOR] hair',
	'Short straight [COLOR] hair',
	'Short curly [COLOR] hair',
	'Short frizzy [COLOR] hair',
	'Short wavy [COLOR] hair',
	'Short straight [COLOR] hair',
	'Short curly [COLOR] hair',
	'Short frizzy [COLOR] hair',
	'Short wavy [COLOR] hair',
	'Short straight [COLOR] hair',
	'Short curly [COLOR] hair',
	'Short frizzy [COLOR] hair',
	'Short [COLOR] hair with dreadlocks',
	'Short [COLOR] hair with cornrows',
	'Short bob [COLOR] hair',
	'Short messy [COLOR] hair',
	'Short messy [COLOR] hair',
	'Short cropped [COLOR] hair',
	'Short spiked [COLOR] hair',
	'Short flat top [COLOR] hair',
	'Short crew cut [COLOR] hair',
	'Short flat top [COLOR] hair',
	'Short crew cut [COLOR] hair',
	'Short flat top [COLOR] hair',
	'Short crew cut [COLOR] hair',
	'Short crew cut [COLOR] hair',
	'Short bowl cut [COLOR] hair',
	'Short bowl cut [COLOR] hair',
	'Short bowl cut [COLOR] hair',
	'Short shaved [COLOR] hair',
	'Short shaved [COLOR] hair',
	'Short shaved [COLOR] hair',
	'Short shaved [COLOR] hair',
	'Long [COLOR] hair balding on top',
	'Long [COLOR] hair with receiding hairline',
	'Shaved head',
	'Bald head',
	'Shoulder length [COLOR] hair balding on top',
	'Shoulder length [COLOR] hair with receiding hairline',
	'Shaved head',
	'Bald head',
	'Short [COLOR] hair balding on top',
	'Short [COLOR] hair with receiding [COLOR] hairline',
	'Shaved head',
	'Bald head',
];
