import {Ancestries} from '../../../constants';

enum SkinColor {
	Pale = 'Pale',
	Pink = 'Pinkysh-white',
	Yellow = 'Yellowish-white',
	MediumWhite = 'Medium white',
	LightBrown = 'Light brown',
	Brown = 'Moderate brown',
	Red = 'Reddish-brown',
	DarkBrown = 'Dark brown',
	DarkRed = 'Dark reddish-brown',
	VeryDarkBrown = 'Very dark brown',
	Black = 'Black',
	Unnatural = 'Unnatural colored',
}

export const SKIN_TONES = [
	SkinColor.Pale,
	SkinColor.Pink,
	SkinColor.Yellow,
	SkinColor.MediumWhite,
	SkinColor.LightBrown,
	SkinColor.Brown,
	SkinColor.Red,
	SkinColor.DarkBrown,
	SkinColor.DarkRed,
	SkinColor.VeryDarkBrown,
	SkinColor.Black,
	SkinColor.Unnatural,
];

export const PREDOMINANT_SKIN_TONE_BY_ANCESTRY = {
	[Ancestries.Anglosaxon]: [
		SkinColor.Pale,
		SkinColor.Pink,
		SkinColor.Pink,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
	],
	[Ancestries.African]: [
		SkinColor.DarkBrown,
		SkinColor.VeryDarkBrown,
		SkinColor.DarkBrown,
		SkinColor.VeryDarkBrown,
		SkinColor.Black,
	],
	[Ancestries.Arabic]: [
		SkinColor.MediumWhite,
		SkinColor.LightBrown,
		SkinColor.MediumWhite,
		SkinColor.LightBrown,
		SkinColor.Brown,
	],
	[Ancestries.Chinese]: [SkinColor.Yellow, SkinColor.Yellow, SkinColor.Pale, SkinColor.MediumWhite],
	[Ancestries.Dutch]: [SkinColor.Pale, SkinColor.Pink, SkinColor.Pink, SkinColor.MediumWhite, SkinColor.MediumWhite],
	[Ancestries.Eastern]: [
		SkinColor.Pale,
		SkinColor.Pink,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.LightBrown,
		SkinColor.LightBrown,
	],
	[Ancestries.French]: [
		SkinColor.Pink,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.LightBrown,
	],
	[Ancestries.Germanic]: [SkinColor.Pale, SkinColor.Pink, SkinColor.Pink, SkinColor.MediumWhite, SkinColor.MediumWhite],
	[Ancestries.Indian]: [
		SkinColor.Brown,
		SkinColor.DarkBrown,
		SkinColor.DarkBrown,
		SkinColor.Red,
		SkinColor.DarkRed,
		SkinColor.DarkRed,
	],
	[Ancestries.Irish]: [SkinColor.Pale, SkinColor.Pink, SkinColor.MediumWhite],
	[Ancestries.Ironlander]: [
		SkinColor.Pale,
		SkinColor.Pale,
		SkinColor.Pale,
		SkinColor.Pink,
		SkinColor.Pink,
		SkinColor.Yellow,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.LightBrown,
		SkinColor.LightBrown,
		SkinColor.Brown,
		SkinColor.Red,
		SkinColor.DarkBrown,
		SkinColor.DarkRed,
		SkinColor.VeryDarkBrown,
		SkinColor.Black,
	],
	[Ancestries.Italian]: [SkinColor.MediumWhite, SkinColor.MediumWhite, SkinColor.MediumWhite, SkinColor.LightBrown],
	[Ancestries.Japanese]: [SkinColor.Yellow, SkinColor.Yellow, SkinColor.Pale],
	[Ancestries.Korean]: [SkinColor.Yellow, SkinColor.Pale],
	[Ancestries.Norse]: [SkinColor.Pale, SkinColor.Pink, SkinColor.MediumWhite],
	[Ancestries.Portuguese]: [SkinColor.MediumWhite, SkinColor.MediumWhite, SkinColor.LightBrown, SkinColor.Brown],
	[Ancestries.Russian]: [
		SkinColor.Pale,
		SkinColor.Pink,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.LightBrown,
		SkinColor.Yellow,
	],
	[Ancestries.Spanish]: [
		SkinColor.MediumWhite,
		SkinColor.MediumWhite,
		SkinColor.LightBrown,
		SkinColor.Brown,
		SkinColor.Red,
	],
	[Ancestries.Fantastic]: [
		SkinColor.Pale,
		SkinColor.Pale,
		SkinColor.Pale,
		SkinColor.Pale,
		SkinColor.Pale,
		SkinColor.Pink,
		SkinColor.Yellow,
		SkinColor.MediumWhite,
		SkinColor.LightBrown,
		SkinColor.Brown,
		SkinColor.Red,
		SkinColor.DarkBrown,
		SkinColor.DarkRed,
		SkinColor.VeryDarkBrown,
		SkinColor.Black,
		SkinColor.Unnatural,
		SkinColor.Unnatural,
		SkinColor.Unnatural,
		SkinColor.Unnatural,
		SkinColor.Unnatural,
	],
};
